<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GMap.NET.Core" Version="2.1.7" />
    <PackageReference Include="GMap.NET.WinForms" Version="2.1.7" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.Drawing.Common" Version="4.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MapsDesignerObject\MapsDesignerObject.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="combit.ListLabel31">
      <HintPath>..\..\..\Assemblies\combit.ListLabel31.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
