using Avalonia;
using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Platform.Storage;

using combit.Reporting;
using combit.Reporting.DataProviders;

using Microsoft.Data.Sqlite;
using Microsoft.Win32;

using ReactiveUI;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;

namespace Export
{
    public partial class MainWindow : Window
    {
        internal ListLabel LL;
        private string? _databasePath = Path.Combine(GetSamplesDirectory(), "northwind.db");
        private string _startPath;
        private string? _fileFilter;
        private LlExportTarget _exporterTarget = LlExportTarget.Pdf;
        private CheckBox? _showFileCheck;
        private string _exportBase = "export.pdf";

        public static string GetSamplesDirectory()
        {
            return Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "..", ".."));
        }

        public static string GetReportFilesDirectory()
        {
            return Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "..", "Report Files", "Cross Platform"));
        }

        private string FileName
        {
            get => fileNameTB.Text ?? string.Empty;
            set { fileNameTB.Text = value; }
        }
        public MainWindow()
        {
            InitializeComponent();

            System.Diagnostics.Debug.WriteLine("Starting project");

            LL = new ListLabel();

            if (String.IsNullOrEmpty(_databasePath))
            {
                System.Diagnostics.Debug.WriteLine("Unable to find sample database. Make sure List & Label is installed correctly.");
            }

            // Change Directory
            _startPath = GetReportFilesDirectory();

            FileName = Path.Combine(_startPath, _exportBase);
            formatComboBox.SelectedIndex = 3;

            // Run this to initialize _fileFilter
            //FormatComboBox_SelectionChanged(this, SelectionChangedEventArgs());

            _showFileCheck = this.FindControl<CheckBox>("showFileCheck");
        }

       

        // Init Data Reader to access northwind.sqlite
        private SqliteCommand CreateSqliteCommand()
        {
            var conn = new SqliteConnection($"Data Source={_databasePath};");

            conn.Open();

            return new SqliteCommand("SELECT * FROM [Products] INNER JOIN [Categories] ON [Products].[CategoryID] = [Categories].[CategoryID]", conn);
        }

        private void createButton_Click(object? sender, RoutedEventArgs e)
        {
            try
            {
                using var cmd = CreateSqliteCommand();

                DbCommandSetDataProvider provider = new DbCommandSetDataProvider();
                provider.AddCommand(cmd, "Products", "[{0}]", "?");
                provider.MinimalSelect = false;
                LL.SetDataBinding(provider, "Products");

                LL.ExportOptions.Clear();

                LL.ExportOptions.Add("LlExportOptions.PdfConformance", "pdfa1a");

                ExportConfiguration exportConfiguration = new ExportConfiguration(_exporterTarget, fileNameTB.Text, Path.Combine(GetReportFilesDirectory(), "simple.json"));
                exportConfiguration.ShowResult = _showFileCheck != null && _showFileCheck.IsChecked == true;

                LL.Export(exportConfiguration);

                System.Diagnostics.Debug.WriteLine("Export completed successfully.");
            }
            catch (ListLabelException LlException)
            {
                System.Diagnostics.Debug.WriteLine("Information: " + LlException.Message + "\n\nThis information was generated by a List & Label custom exception.");
            }

            catch (Exception ex)
            {
                // Show any other errors
                System.Diagnostics.Debug.WriteLine("Error: " + ex.Message);
            }
        }

        private async void selectButton_Click(object? sender, RoutedEventArgs e)
        {
            if (_fileFilter == null) return;

            var fileTypes = new List<FilePickerFileType>
            {
                new FilePickerFileType("Export")
                {
                    Patterns = new [] {_fileFilter ?? "*.pdf" }
                }
            };

            var options = new FilePickerSaveOptions
            {
                SuggestedFileName = Path.GetFileName(FileName),
                FileTypeChoices = fileTypes
            };

            var result = await this.StorageProvider.SaveFilePickerAsync(options);

            if (result != null)
            {
                FileName = result.Path.LocalPath;
            }
        }

        private void FormatComboBox_SelectionChanged(object? sender, SelectionChangedEventArgs e)
        {
            if (fileNameTB == null) return;

            string directory = Path.GetDirectoryName(fileNameTB.Text) ?? "";
            string baseName = Path.GetFileNameWithoutExtension(fileNameTB.Text) ?? "";

            switch ((formatComboBox.SelectedItem as ComboBoxItem)?.Content?.ToString())
            {
                case "CSV":
                    _fileFilter = "CSV files|*.csv";
                    _exporterTarget = LlExportTarget.Csv;
                    _exportBase = baseName + ".csv";
                    break;
                case "JPEG":
                    _fileFilter = "JPEG files|*.jpg";
                    _exporterTarget = LlExportTarget.Jpeg;
                    _exportBase = baseName + ".jpg";
                    break;
                case "JSON":
                    _fileFilter = "JSON files|*.json";
                    _exporterTarget = LlExportTarget.Json;
                    _exportBase = baseName + ".json";
                    break;
                case "PDF":
                    _fileFilter = "PDF files|*.pdf";
                    _exporterTarget = LlExportTarget.Pdf;
                    _exportBase = baseName + ".pdf";
                    break;
                case "PNG":
                    _fileFilter = "PNG files|*.png";
                    _exporterTarget = LlExportTarget.Png;
                    _exportBase = baseName + ".png";
                    break;
                case "SVG":
                    _fileFilter = "SVG files|*.svg";
                    _exporterTarget = LlExportTarget.Svg;
                    _exportBase = baseName + ".svg";
                    break;
                case "XLSX":
                    _fileFilter = "XLSX files|*.xlsx";
                    _exporterTarget = LlExportTarget.Xlsx;
                    _exportBase = baseName + ".xlsx";
                    break;
            }
            FileName = Path.Combine(directory, _exportBase);
        }
    }
}