//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace combit.ListLabel.MapsObject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("combit.ListLabel.MapsObject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the City.
        /// </summary>
        internal static string CityDescr {
            get {
                return ResourceManager.GetString("CityDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate Evaluation Type.
        /// </summary>
        internal static string CoordinateEvaluationType {
            get {
                return ResourceManager.GetString("CoordinateEvaluationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Type of Coordinate Evaluation (Geocoding or Coordinates).
        /// </summary>
        internal static string CoordinateEvaluationTypeDescr {
            get {
                return ResourceManager.GetString("CoordinateEvaluationTypeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude for dislaying.
        /// </summary>
        internal static string LatitudeDescr {
            get {
                return ResourceManager.GetString("LatitudeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude for displaying.
        /// </summary>
        internal static string LongitudeDescr {
            get {
                return ResourceManager.GetString("LongitudeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MapsObj {
            get {
                object obj = ResourceManager.GetObject("MapsObj", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Type.
        /// </summary>
        internal static string MapType {
            get {
                return ResourceManager.GetString("MapType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Map Type.
        /// </summary>
        internal static string MapTypeDescr {
            get {
                return ResourceManager.GetString("MapTypeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution for displaying.
        /// </summary>
        internal static string ResolutionDescr {
            get {
                return ResourceManager.GetString("ResolutionDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tooltip.
        /// </summary>
        internal static string ShowToolTip {
            get {
                return ResourceManager.GetString("ShowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines whether the Tooltip is displayed.
        /// </summary>
        internal static string ShowToolTipDescr {
            get {
                return ResourceManager.GetString("ShowToolTipDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip Background.
        /// </summary>
        internal static string ToolTipBg {
            get {
                return ResourceManager.GetString("ToolTipBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color for Tooltip Background.
        /// </summary>
        internal static string ToolTipBgDescr {
            get {
                return ResourceManager.GetString("ToolTipBgDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip font.
        /// </summary>
        internal static string ToolTipFont {
            get {
                return ResourceManager.GetString("ToolTipFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Font for Tooltip.
        /// </summary>
        internal static string ToolTipFontDescr {
            get {
                return ResourceManager.GetString("ToolTipFontDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tooltip Text.
        /// </summary>
        internal static string ToolTipText {
            get {
                return ResourceManager.GetString("ToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text displayed in Tooltip.
        /// </summary>
        internal static string ToolTipTextDescr {
            get {
                return ResourceManager.GetString("ToolTipTextDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Level.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Level for displaying.
        /// </summary>
        internal static string ZoomDescr {
            get {
                return ResourceManager.GetString("ZoomDescr", resourceCulture);
            }
        }
    }
}
