Imports System.IO
Imports System.Windows.Forms

Public Partial Class Form1
    Inherits Form
    Public Sub New()
		InitializeComponent()

        'D: Pfad auf Sample-Hauptverzeichnis setzen
        'US: Set path to main sample path
        Directory.SetCurrentDirectory(Application.StartupPath & "\..\..\..\..\..\..\Report Files")
    End Sub

    Private Sub DesignBtn_Click(sender As Object, e As EventArgs) Handles designBtn.Click
        Dim provider As New CsvDataProvider(Path.Combine(Application.StartupPath, "test.txt"))
        Dim ll As New ListLabel()
        ll.DataSource = provider
        ll.AutoProjectFile = "CsvDataProvider.lst"
        Try
            ll.Design()
        Catch LlException As ListLabelException
            ' Catch Exceptions
            MessageBox.Show("Information: " & LlException.Message & vbLf & vbLf & "This information was generated by a List & Label custom exception.", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information)
        End Try
        ll.Dispose()
    End Sub

    Private Sub PrintBtn_Click(sender As Object, e As EventArgs) Handles printBtn.Click
        Dim provider As New CsvDataProvider(Path.Combine(Application.StartupPath, "test.txt"))
        Dim ll As New ListLabel()
        ll.DataSource = provider
        ll.AutoProjectFile = "CsvDataProvider.lst"
        Try
            ll.Print()
        Catch LlException As ListLabelException
            ' Catch Exceptions
            MessageBox.Show("Information: " & LlException.Message & vbLf & vbLf & "This information was generated by a List & Label custom exception.", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information)
        End Try

        ll.Dispose()
    End Sub
End Class
