


USING ListLabelDemo.Sports2000DemoForm FROM PROPATH.

DEFINE VARIABLE oForm AS Sports2000DemoForm NO-UNDO.

SESSION:SYSTEM-ALERT-BOXES = TRUE.
FILE-INFO:FILE-NAME = ".".
PROPATH = FILE-INFO:FULL-PATHNAME + "," + PROPATH.

DO ON ERROR  UNDO, LEAVE
	ON ENDKEY UNDO, LEAVE
	ON STOP   UNDO, LEAVE
	ON QUIT   UNDO, LEAVE:
	oForm = NEW Sports2000DemoForm ( ) .
	WAIT-FOR System.Windows.Forms.Application:Run ( oForm ).
	DEFINE VARIABLE i AS INTEGER NO-UNDO.
	CATCH e1 AS Progress.Lang.AppError:
	DO i = 1 TO e1:NumMessages:
		MESSAGE e1:GetMessage(i) VIEW-AS ALERT-BOX BUTTONS OK TITLE "Error".
	END.
	IF e1:ReturnValue > "" THEN
		MESSAGE e1:ReturnValue VIEW-AS ALERT-BOX BUTTONS OK TITLE "Return Value".
	END CATCH.
	CATCH e2 AS Progress.Lang.Error:
		DO i = 1 TO e2:NumMessages:
			MESSAGE e2:GetMessage(i) VIEW-AS ALERT-BOX BUTTONS OK TITLE "Error".
		END.
	END CATCH.
END.
QUIT.
FINALLY.
    IF VALID-OBJECT(oForm) THEN 
        DELETE OBJECT oForm NO-ERROR.
END FINALLY.
