#if !defined(AFX_LLRTFCTRL_H__6C4D791B_D338_4155_BA51_E8B93E82E4D1__INCLUDED_)
#define AFX_LLRTFCTRL_H__6C4D791B_D338_4155_BA51_E8B93E82E4D1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLlRtfCtrl wrapper class

class CLlRtfCtrl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CLlRtfCtrl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xc78b7bcd, 0x03b4, 0x412f, { 0xa2, 0x5e, 0x62, 0xda, 0x8a, 0x4d, 0x2e, 0x0F } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	long GetTextMode();
	void SetTextMode(long nNewValue);
	LPDISPATCH GetParentComponent();
	void SetParentComponent(LPDISPATCH newValue);
	long GetContentMode();
	void SetContentMode(long nNewValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	long GetPrintState();
	void CopyToClipboard();
	void ProhibitAction(long ControlID);
	void Display(long hDC, long left, long top, long right, long bottom, BOOL bRestart);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LLRTFCTRL_H__6C4D791B_D338_4155_BA51_E8B93E82E4D1__INCLUDED_)
