#if !defined(AFX_LUL_H__1A640ACF_A93E_41AD_8BC9_0D5264CD0206__INCLUDED_)
#define AFX_LUL_H__1A640ACF_A93E_41AD_8BC9_0D5264CD0206__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLul wrapper class

class CLul : public CWnd
{
protected:
	DECLARE_DYNCREATE(CLul)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2213e280, 0x16bc, 0x101d, { 0xaf, 0xd4, 0x04, 0x02, 0x24, 0x00, 0x9d, 0xf8 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetLanguage();
	void SetLanguage(long);
	long GetDialogMode();
	void SetDialogMode(long);
	long GetDialogFrame();
	void SetDialogFrame(long);
	long GetDialog3DText();
	void SetDialog3DText(long);
	long GetDialogButtons();
	void SetDialogButtons(long);
	BOOL GetEnablePageCallback();
	void SetEnablePageCallback(BOOL);
	BOOL GetEnableProjectCallback();
	void SetEnableProjectCallback(BOOL);
	BOOL GetEnableObjectCallback();
	void SetEnableObjectCallback(BOOL);
	long GetNewExpressions();
	void SetNewExpressions(long);
	BOOL GetEnableHelpCallback();
	void SetEnableHelpCallback(BOOL);
	BOOL GetOnlyOneTable();
	void SetOnlyOneTable(BOOL);
	BOOL GetMultipleTableLines();
	void SetMultipleTableLines(BOOL);
	long GetTableColoring();
	void SetTableColoring(long);
	long GetTabStops();
	void SetTabStops(long);
	BOOL GetSortVariables();
	void SetSortVariables(BOOL);
	BOOL GetHelpAvailable();
	void SetHelpAvailable(BOOL);
	BOOL GetShowPredefVars();
	void SetShowPredefVars(BOOL);
	BOOL GetUseHostprinter();
	void SetUseHostprinter(BOOL);
	long GetEMFResolution();
	void SetEMFResolution(long);
	BOOL GetAddVarsToFields();
	void SetAddVarsToFields(BOOL);
	BOOL GetConvertCRLF();
	void SetConvertCRLF(BOOL);
	BOOL GetWizFileNew();
	void SetWizFileNew(BOOL);
	BOOL GetVarsCaseSensitive();
	void SetVarsCaseSensitive(BOOL);
	BOOL GetRealTime();
	void SetRealTime(BOOL);
	BOOL GetSpaceOptimization();
	void SetSpaceOptimization(BOOL);
	BOOL GetCompressStorage();
	void SetCompressStorage(BOOL);
	BOOL GetNoParameterCheck();
	void SetNoParameterCheck(BOOL);
	BOOL GetNoNoTableCheck();
	void SetNoNoTableCheck(BOOL);
	long GetPreviewZoomPerc();
	void SetPreviewZoomPerc(long);
	long GetPreviewRectLeft();
	void SetPreviewRectLeft(long);
	long GetPreviewRectTop();
	void SetPreviewRectTop(long);
	long GetPreviewRectWidth();
	void SetPreviewRectWidth(long);
	long GetPreviewRectHeight();
	void SetPreviewRectHeight(long);
	long GetMetric();
	void SetMetric(long);
	short GetTabRepresentationCode();
	void SetTabRepresentationCode(short);
	short GetRetRepresentationCode();
	void SetRetRepresentationCode(short);
	long GetStorageSystem();
	void SetStorageSystem(long);
	BOOL GetAutoMultipage();
	void SetAutoMultipage(BOOL);
	BOOL GetUseBarcodeSizes();
	void SetUseBarcodeSizes(BOOL);
	short GetMaxRTFVersion();
	void SetMaxRTFVersion(short);
	BOOL GetDelayTableHeader();
	void SetDelayTableHeader(BOOL);
	BOOL GetOfnDialogExplorer();
	void SetOfnDialogExplorer(BOOL);
	BOOL GetCreateInfo();
	void SetCreateInfo(BOOL);
	BOOL GetXlatVarNames();
	void SetXlatVarNames(BOOL);
	short GetPhantomSpaceRepresentationCode();
	void SetPhantomSpaceRepresentationCode(short);
	short GetLockNextCharRepresentationCode();
	void SetLockNextCharRepresentationCode(short);
	short GetExprSepRepresentationCode();
	void SetExprSepRepresentationCode(short);
	short GetTextQuoteRepresentationCode();
	void SetTextQuoteRepresentationCode(short);
	BOOL GetInterCharSpacing();
	void SetInterCharSpacing(BOOL);
	BOOL GetIncludeFontDescent();
	void SetIncludeFontDescent(BOOL);
	BOOL GetUseChartFields();
	void SetUseChartFields(BOOL);
	CString GetProjectPassword();
	void SetProjectPassword(LPCTSTR);
	CString GetLicensingInfo();
	void SetLicensingInfo(LPCTSTR);
	BOOL GetIncrementalPreview();
	void SetIncrementalPreview(BOOL);
	BOOL GetEnabled();
	void SetEnabled(BOOL);

// Operations
public:
	long LlGetVersion(long nCmd);
	void LlSetDebug(long nFlags);
	long LlDefineField(LPCTSTR sVarName, LPCTSTR sContent);
	long LlDefineVariable(LPCTSTR sVarName, LPCTSTR sContent);
	long LlDefineFieldExt(LPCTSTR sVarName, LPCTSTR sContent, long nFieldType);
	long LlDefineVariableExt(LPCTSTR sVarName, LPCTSTR sContent, long nFieldType);
	void LlDefineFieldStart();
	void LlDefineVariableStart();
	long LlDefineSumVariable(LPCTSTR sVarName, LPCTSTR sContent);
	long LlDefineFieldExtHandle(LPCTSTR sVarName, long hContent, long nFieldType);
	long LlDefineVariableExtHandle(LPCTSTR sVarName, long hContent, long nFieldType);
	long LlDefineLayout(long hWnd, LPCTSTR sTitle, long nObjType, LPCTSTR sObjName);
	long LlPrint();
	long LlPrintAbort();
	long LlPrintFields();
	long LlPrintFieldsEnd();
	long LlPrintEnd(long nPages);
	long LlPrintGetCurrentPage();
	BOOL LlPrintCheckLineFit();
	long LlPrintGetItemsPerPage();
	long LlPrintGetItemsPerTable();
	long LlPrintGetRemItemsPerTable(LPCTSTR sField);
	long LlPreviewSetTempPath(LPCTSTR sPath);
	long LlPreviewDeleteFiles(LPCTSTR sObjName, LPCTSTR sPath);
	long LlPreviewDisplay(LPCTSTR sObjName, LPCTSTR sPath, long hWnd);
	long LlPreviewDisplayEx(LPCTSTR sObjName, LPCTSTR sPath, long hWnd, long nOptions);
	long LlSetOption(long nMode, long nValue);
	long LlPrinterSetup(long hWnd, long nObjType, LPCTSTR sObjName);
	long LlPrintSetBoxText(LPCTSTR sText, long nPercentage);
	long LlPrintIsVariableUsed(LPCTSTR sVarName);
	long LlPrintIsFieldUsed(LPCTSTR sFieldName);
	long LlPrintEnableObject(LPCTSTR sObjName, long bEnable);
	long LlPrintWillMatchFilter();
	long LlPrintDidMatchFilter();
	long LlPrintStart(long nObjType, LPCTSTR sObjName, long nPrintOptions);
	long LlPrintWithBoxStart(long nObjType, LPCTSTR sObjName, long nPrintOptions, long nBoxType, long hWnd, LPCTSTR sTitle);
	long LlPrintOptionsDialog(long hWnd, LPCTSTR sText);
	long LlSetPrinterDefaultsDir(LPCTSTR sDir);
	long LlAddCtlSupport(long hWnd, long nFlags, LPCTSTR sIniFile);
	long LlSetFileExtensions(long nObjType, LPCTSTR sObjectExt, LPCTSTR sPrinterExt, LPCTSTR sSketchExt);
	long LlSetPrinterToDefault(long nObjType, LPCTSTR sObjName);
	long LlPrintSetOption(long nIndex, long nValue);
	long LlPrintOptionsDialogTitle(long hWnd, LPCTSTR sTitle, LPCTSTR sText);
	long LlDefineSortOrderStart();
	long LlDefineSortOrder(LPCTSTR sIdentifier, LPCTSTR sText);
	long LlPrintGetSortOrder(BSTR* psBuffer);
	long LlDefineGrouping(LPCTSTR sSortorder, LPCTSTR sIdentifier, LPCTSTR sText);
	long LlPrintGetGrouping(BSTR* psBuffer);
	long LlGetOption(long nMode);
	long LlSetOptionString(long nIndex, LPCTSTR sBuffer);
	long LlGetOptionString(long nIndex, BSTR* psBuffer);
	long LlGetVariableContents(LPCTSTR sName, BSTR* psBuffer);
	long LlGetFieldContents(LPCTSTR sName, BSTR* psBuffer);
	long LlGetSumVariableContents(LPCTSTR sName, BSTR* psBuffer);
	long LlGetUserVariableContents(LPCTSTR sName, BSTR* psBuffer);
	long LlGetVariableType(LPCTSTR sName);
	long LlGetFieldType(LPCTSTR sName);
	long LlPrintGetOption(long nIndex);
	long LlPrintGetPrinterInfo(BSTR* psPrn, BSTR* psPort);
	long LlPrintGetFilterExpression(BSTR* psBuffer);
	long LlSelectFileDlg(long hWnd, long nObjType, BSTR* psObjName);
	long LlSelectFileDlgTitle(long hWnd, LPCTSTR sTitle, long nObjType, BSTR* psObjName);
	long LlPrintSelectOffset(long hWnd);
	long LlDesignerProhibitAction(long nMenuID);
	long LlExprParse(LPCTSTR sExprText, long bTablefields);
	long LlExprType(long nptrExpr);
	void LlExprError(BSTR* psBuffer);
	void LlExprFree(long nptrExpr);
	long LlExprEvaluate(long nptrExpr, BSTR* psBuffer);
	long LlDlgEditLineEx(long hWnd, BSTR* psBuffer, long nParaTypes, LPCTSTR sTitle, long bTable);
	long LlSetDecimalChar(long cDecPoint);
	long LlCreateSketch(long nObjType, LPCTSTR sObjName);
	long LlViewerProhibitAction(long nMenuID);
	long LlPrintCopyPrinterConfiguration(LPCTSTR sFileName, long nFunction);
	long LlStgsysStorageOpen(LPCTSTR sFileName, LPCTSTR sTempPath, long bReadOnly, long bOneJobTranslation);
	void LlStgsysStorageClose(long hStg);
	long LlStgsysGetAPIVersion(long hStg);
	long LlStgsysGetFileVersion(long hStg);
	long LlStgsysGetJobCount(long hStg);
	long LlStgsysGetPageCount(long hStg);
	long LlStgsysGetLastError(long hStg);
	long LlStgsysDeleteFiles(long hStg);
	long LlStgsysAppend(long hStg, long hStgToAppend);
	long LlStgsysSetJob(long hStg, long nJob);
	long LlStgsysGetFilename(long hStg, long nJob, long nFile, BSTR* psBuffer);
	long LlStgsysGetJobOptionValue(long hStg, long nOption);
	long LlStgsysGetPageOptionValue(long hStg, long nPageIndex, long nOption);
	long LlStgsysSetPageOptionString(long hStg, long nPageIndex, long nOption, LPCTSTR sBuffer);
	long LlStgsysGetPageOptionString(long hStg, long nPageIndex, long nOption, BSTR* psBuffer);
	long LlStgsysGetPageMetafile(long hStg, long nPageIndex);
	long LlStgsysGetPageMetafile16(long hStg, long nPageIndex);
	long LlStgsysDestroyMetafile(long hMF);
	long LlStgsysDrawPage(long hStg, long hDC, long hPrnDC, long bAskPrinter, long left, long top, long right, long bottom, long nPageIndex, long bFit);
	long LlPrintSetOptionString(long nIndex, LPCTSTR sBuffer);
	long LlPrintGetOptionString(long nIndex, BSTR* psBuffer);
	long Design(long nUserData, long hWnd, LPCTSTR sTitle, long nObjType, LPCTSTR sObjName, long bWithFileSelect);
	long Print(long nUserData, long nObjType, LPCTSTR sObjName, long bWithFileSelect, long nPrintOptions, long nBoxType, long hWnd, LPCTSTR sTitle, long bShowPrintOptionsDlg, LPCTSTR sTempPath);
	void LlDebugOutput(long nIdent, LPCTSTR sText);
	long LlEnumGetFirstVar(long nFlags);
	long LlEnumGetFirstField(long nFlags);
	long LlEnumGetNextEntry(long nPos, long nFlags);
	long LlEnumGetEntry(long nPos, BSTR* psName, BSTR* psContents, long* pHandle, long* pnType);
	long LlXGetParameter(long nExtensionType, LPCTSTR sExtensionName, LPCTSTR sKey, BSTR* psBuffer);
	long LlXSetParameter(long nExtensionType, LPCTSTR sExtensionName, LPCTSTR sKey, LPCTSTR sValue);
	long LlPrintResetObjectStates();
	long LlStgsysPrint(long hStg, LPCTSTR sPrinterName1, LPCTSTR sPrinterName2, long nStartPageIndex, long nEndPageIndex, long nCopies, long nFlags, LPCTSTR sMessage, long hWnd);
	long LlStgsysStoragePrint(LPCTSTR sFileName, LPCTSTR sTempPath, LPCTSTR sPrinterName1, LPCTSTR sPrinterName2, long nStartPageIndex, long nEndPageIndex, long nCopies, long nFlags, LPCTSTR sMessage, long hWnd);
	long LlPrintResetProjectState();
	long LlSetPrinterInPrinterFile(long nObjType, LPCTSTR sObjName, long nPrinter, LPCTSTR sPrinter, long pDevMode);
	long LlDesignerProhibitFunction(LPCTSTR sFunctionName);
	long LlDefineChartFieldExt(LPCTSTR sVarName, LPCTSTR sContent, long nFieldType);
	long LlDefineChartFieldStart();
	long LlPrintDeclareChartRow(long nFlags);
	long LlPrintIsChartFieldUsed(LPCTSTR sFieldName);
	long LlGetChartFieldContents(LPCTSTR sName, BSTR* psBuffer);
	long LlEnumGetFirstChartField(long nFlags);
	long LlPrintGetChartObjectCount(long nFlags);
	long LlRTFCreateObject();
	long LlRTFDeleteObject(long hRTFObj);
	long LlRTFSetText(long hRTFObj, LPCTSTR sText);
	long LlRTFGetTextLength(long hRTFObj, long nFlags);
	long LlRTFGetText(long hRTFObj, long nFlags, BSTR* psText);
	long LlRTFEditObject(long hRTFObj, long hWnd, long hPrnDC, long nProjectType, long bModal);
	long LlRTFCopyToClipboard(long hRTFObj);
	long LlPrintGetRemainingSpacePerTable(LPCTSTR sField, long nDimension);
	long LlRTFDisplay(long hRTFObj, long hDC, long* left, long* top, long* right, long* bottom, long bRestart, long* pnState);
	long LlStgsysConvert(long hStg, LPCTSTR sDestFilename, LPCTSTR sFormat);
	long LlSetDefaultProjectParameter(LPCTSTR sParam, LPCTSTR sValue, long nFlags);
	long LsMailConfigurationDialog(long hWndParent, LPCTSTR sSubKey, long nFlags, long nLanguage);
	long LlDbAddTable(LPCTSTR sTableID, LPCTSTR sDisplayName);
	long LlDbAddTableRelation(LPCTSTR sTableID, LPCTSTR sParentTableID, LPCTSTR sRelationID, LPCTSTR sRelationDisplayName);
	long LlDbAddTableSortOrder(LPCTSTR sTableID, LPCTSTR sSortOrderID, LPCTSTR sSortOrderDisplayName);
	long LlDbSetMasterTable(LPCTSTR sTableID);
	long LlPrintDbGetCurrentTable(BSTR* psTableID, long bCompletePath);
	long LlPrintDbGetCurrentTableSortOrder(BSTR* psSortOrderID);
	long LlPrintDbGetCurrentTableRelation(BSTR* psRelationID);
	long LlPrintDbGetRootTableCount();
	long LlPrintSetProjectParameter(LPCTSTR sParam, LPCTSTR sValue, long nFlags);
	long LlPrintGetProjectParameter(LPCTSTR sParam, long bEvaluated, BSTR* psValue, long* pnFlags);
	long LlGetDefaultProjectParameter(LPCTSTR sParam, BSTR* psValue, long* pnFlags);
	long LlDesignerProhibitEditingObject(LPCTSTR sObject);
	long LsMailJobOpen(long nLanguage);
	long LsMailJobClose(long hMailJob);
	long LsMailSetOptionString(long hMailJob, LPCTSTR sKey, LPCTSTR sValue);
	long LsMailSendFile(long hMailJob, long hWndParent);
	long LlGetUsedIdentifiers(LPCTSTR sProjectName, BSTR* psBuffer);
	long LlDictionaryAdd(long nDictionaryType, LPCTSTR sName, LPCTSTR sNameTranslated);
	long LlDictionariesClear();
	long LlDomGetProject(long* phDOMObj);
	long LlDomGetProperty(long hDOMObj, LPCTSTR sName, BSTR* psValue);
	long LlDomSetProperty(long hDOMObj, LPCTSTR sName, LPCTSTR sValue);
	long LlDomGetObject(long hDOMObj, LPCTSTR sName, long* phDOMObj);
	long LlDomGetSubobject(long hDOMObj, long nPosition, long* phDOMObj);
	long LlDomCreateSubobject(long hDOMObj, long nPosition, LPCTSTR sType, long* phDOMObj);
	long LlDomDeleteSubobject(long hDOMObj, long nPosition);
	long LlProjectOpen(long nObjType, LPCTSTR sProjectName, long nOpenMode);
	long LlProjectSave(LPCTSTR sProjectName);
	long LlProjectClose();
	long LlAssociatePreviewControl(long hWndControl, long nFlags);
	long LlGetErrortext(long nErrorCode, BSTR* psErrorText);
	long LlDomGetSubobjectCount(long hDOMObj, long* nCount);
	long LlDesignerInvokeAction(long nMenuID);
	long LlDesignerRefreshWorkspace();
	long LlDesignerFileOpen(LPCTSTR sFileName, long nFlags);
	long LlDesignerFileSave(long nFlags);
	long LlDesignerAddAction(long nID, long nFlags, LPCTSTR sMenuText, LPCTSTR sMenuHierarchy, LPCTSTR sTooltipText, long nIcon, long nReserved);
	long LlDesignerGetOptionString(long nIndex, BSTR* psBuffer);
	long LlDesignerSetOptionString(long nIndex, LPCTSTR sBuffer);
	long LlGetProjectParameter(LPCTSTR sProjectName, LPCTSTR sParam, BSTR* psValue);
	long LlDbAddTableRelationEx(LPCTSTR sTableID, LPCTSTR sParentTableID, LPCTSTR sRelationID, LPCTSTR sRelationDisplayName, LPCTSTR sKeyField, LPCTSTR sParentKeyField);
	long LlDbAddTableSortOrderEx(LPCTSTR sTableID, LPCTSTR sSortOrderID, LPCTSTR sSortOrderDisplayName, LPCTSTR sField);
	long LlLocAddDictionaryEntry(long nLCID, LPCTSTR sKey, LPCTSTR sValue, long nType);
	long LlLocAddDesignLCID(long nLCID);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LUL_H__1A640ACF_A93E_41AD_8BC9_0D5264CD0206__INCLUDED_)
