'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("combit.ListLabel.MapsObject.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City.
        '''</summary>
        Friend ReadOnly Property City() As String
            Get
                Return ResourceManager.GetString("City", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name of the City.
        '''</summary>
        Friend ReadOnly Property CityDescr() As String
            Get
                Return ResourceManager.GetString("CityDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Coordinate Evaluation Type.
        '''</summary>
        Friend ReadOnly Property CoordinateEvaluationType() As String
            Get
                Return ResourceManager.GetString("CoordinateEvaluationType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Used Type of Coordinate Evaluation (Geocoding or Coordinates).
        '''</summary>
        Friend ReadOnly Property CoordinateEvaluationTypeDescr() As String
            Get
                Return ResourceManager.GetString("CoordinateEvaluationTypeDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Latitude.
        '''</summary>
        Friend ReadOnly Property Latitude() As String
            Get
                Return ResourceManager.GetString("Latitude", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Latitude for dislaying.
        '''</summary>
        Friend ReadOnly Property LatitudeDescr() As String
            Get
                Return ResourceManager.GetString("LatitudeDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Longitude.
        '''</summary>
        Friend ReadOnly Property Longitude() As String
            Get
                Return ResourceManager.GetString("Longitude", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Longitude for displaying.
        '''</summary>
        Friend ReadOnly Property LongitudeDescr() As String
            Get
                Return ResourceManager.GetString("LongitudeDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property MapsObj() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MapsObj", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map Type.
        '''</summary>
        Friend ReadOnly Property MapType() As String
            Get
                Return ResourceManager.GetString("MapType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Used Map Type.
        '''</summary>
        Friend ReadOnly Property MapTypeDescr() As String
            Get
                Return ResourceManager.GetString("MapTypeDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resolution.
        '''</summary>
        Friend ReadOnly Property Resolution() As String
            Get
                Return ResourceManager.GetString("Resolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resolution for displaying.
        '''</summary>
        Friend ReadOnly Property ResolutionDescr() As String
            Get
                Return ResourceManager.GetString("ResolutionDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Tooltip.
        '''</summary>
        Friend ReadOnly Property ShowToolTip() As String
            Get
                Return ResourceManager.GetString("ShowToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Defines whether the Tooltip is displayed.
        '''</summary>
        Friend ReadOnly Property ShowToolTipDescr() As String
            Get
                Return ResourceManager.GetString("ShowToolTipDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tooltip Background.
        '''</summary>
        Friend ReadOnly Property ToolTipBg() As String
            Get
                Return ResourceManager.GetString("ToolTipBg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Color for Tooltip Background.
        '''</summary>
        Friend ReadOnly Property ToolTipBgDescr() As String
            Get
                Return ResourceManager.GetString("ToolTipBgDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tooltip font.
        '''</summary>
        Friend ReadOnly Property ToolTipFont() As String
            Get
                Return ResourceManager.GetString("ToolTipFont", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Used Font for Tooltip.
        '''</summary>
        Friend ReadOnly Property ToolTipFontDescr() As String
            Get
                Return ResourceManager.GetString("ToolTipFontDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tooltip Text.
        '''</summary>
        Friend ReadOnly Property ToolTipText() As String
            Get
                Return ResourceManager.GetString("ToolTipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text displayed in Tooltip.
        '''</summary>
        Friend ReadOnly Property ToolTipTextDescr() As String
            Get
                Return ResourceManager.GetString("ToolTipTextDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zoom Level.
        '''</summary>
        Friend ReadOnly Property Zoom() As String
            Get
                Return ResourceManager.GetString("Zoom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zoom Level for displaying.
        '''</summary>
        Friend ReadOnly Property ZoomDescr() As String
            Get
                Return ResourceManager.GetString("ZoomDescr", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
