<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateResourceWarnOnBinaryFormatterUse>false</GenerateResourceWarnOnBinaryFormatterUse>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="combit.ListLabel31">
      <HintPath>..\..\Assemblies\combit.ListLabel31.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
