'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace WebReporting


    Partial Public Class [Default]

        ''' <summary>
        ''' Form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' LinkButtonStart control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LinkButtonStart As Global.System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' DropDownListProjectFile control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected DropDownListProjectFile As Global.System.Web.UI.WebControls.DropDownList

        ''' <summary>
        ''' LinkButtonRefresh control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LinkButtonRefresh As Global.System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' LinkButtonDesign control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LinkButtonDesign As Global.System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' LinkButtonCreate control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected LinkButtonCreate As Global.System.Web.UI.WebControls.LinkButton

        ''' <summary>
        ''' ContentContainer control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ContentContainer As Global.System.Web.UI.HtmlControls.HtmlIframe
    End Class
End Namespace