using System;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Windows.Forms;
using combit.Reporting;

namespace unicode
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            // Change Directory - needed while running within the IDE
            if (!File.Exists("Address.mdb"))
            {
                Directory.SetCurrentDirectory(@"..\..\..\..\..\..\..\Report Files");
            }

            // Do not modify variables
            LL.Core.LlSetOption(LlOption.XlatVarnames, 0);
        }

        // create Dataset from address.mdb
        private DataSet CreateDataSet()
        {
            DataSet ds = new DataSet();
            string connectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + Path.GetDirectoryName(Application.ExecutablePath) + @"..\..\..\..\..\..\..\..\Report Files\Address.mdb";
            OleDbConnection myOledbConnection = new OleDbConnection(connectionString);
            myOledbConnection.Open();

            DataTable table = myOledbConnection.GetSchema("Tables");

            OleDbDataAdapter dataAdapter;
            dataAdapter = new OleDbDataAdapter(new OleDbCommand("SELECT * FROM Persons", myOledbConnection));
            dataAdapter.FillSchema(ds, SchemaType.Source, "Persons");
            dataAdapter.Fill(ds, "Persons");

            return ds;
        }

        private void button1_Click(object sender, EventArgs e)
        {
            //now bind to the DataSet
            LL.SetDataBinding(CreateDataSet(), String.Empty);

            try
            {
                LL.AutoProjectFile = "simple_unicode.lbl";
                LL.AutoProjectType = LlProject.Label;
                LL.AutoShowSelectFile = false;
                LL.Design();
            }
            catch (ListLabelException LlException)
            {
                // Catch Exceptions
                MessageBox.Show("Information: " + LlException.Message + "\n\nThis information was generated by a List & Label custom exception.", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void button3_Click(object sender, EventArgs e)
        {
            //now bind to the DataSet
            LL.SetDataBinding(CreateDataSet(), string.Empty);

            try
            {
                LL.AutoProjectFile = "simple_unicode.lst";
                LL.AutoProjectType = LlProject.List;
                LL.AutoShowSelectFile = false;
                LL.Design();

            }
            catch (ListLabelException LlException)
            {
                // Catch Exceptions
                MessageBox.Show("Information: " + LlException.Message + "\n\nThis information was generated by a List & Label custom exception.", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void button2_Click(object sender, EventArgs e)
        {
            //now bind to the DataSet
            LL.SetDataBinding(CreateDataSet(), string.Empty);

            try
            {
                LL.AutoProjectFile = "simple_unicode.lbl";
                LL.AutoProjectType = LlProject.Label;
                LL.AutoShowSelectFile = false;
                LL.Print();
            }
            catch (ListLabelException LlException)
            {
                // Catch Exceptions
                MessageBox.Show("Information: " + LlException.Message + "\n\nThis information was generated by a List & Label custom exception.", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

        private void button4_Click(object sender, EventArgs e)
        {
            //US: now bind to the DataSet
            LL.SetDataBinding(CreateDataSet(), string.Empty);

            try
            {
                LL.AutoProjectFile = "simple_unicode.lst";
                LL.AutoProjectType = LlProject.List;
                LL.AutoShowSelectFile = false;
                LL.Print();

            }
            catch (ListLabelException LlException)
            {
                // Catch Exceptions
                MessageBox.Show("Information: " + LlException.Message + "\n\nThis information was generated by a List & Label custom exception.", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }
    }
}
