Imports System.Data.OleDb
Imports System.IO
Imports System.Windows.Forms
Imports combit.ListLabel25
Imports combit.ListLabel25.DataProviders
Imports Microsoft.Win32

Public Partial Class Form1
    Inherits Form
    Private _databasePath As String

	Public Sub New()
		InitializeComponent()
        'D: Pfad auf Sample-Hauptverzeichnis setzen, Datenbankpfad auslesen
        'US: Set path to main sample path, read database path
        Directory.SetCurrentDirectory(Application.StartupPath & "\..\..\..\..\..\..\Report Files")
        Dim installKey As RegistryKey = Registry.CurrentUser.CreateSubKey("Software\combit\cmbtll")

		If installKey IsNot Nothing Then
			_databasePath = DirectCast(installKey.GetValue("NWINDPath", String.Empty), String)
		End If

		If _databasePath = String.Empty Then
			MessageBox.Show("Unable to find sample database. Make sure List & Label is installed correctly.", "List & Label")
		End If
	End Sub

	' create Provider
	Private Function CreateDbCommandSetDataProvider() As DbCommandSetDataProvider
		Dim provider As New DbCommandSetDataProvider()
		Dim ConnectionString As String = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" & _databasePath
		Dim myOleDbConnection As New OleDbConnection(ConnectionString)
		myOleDbConnection.Open()
		Dim myOleDbCommand As New OleDbCommand("SELECT * FROM Products", myOleDbConnection)
        provider.AddCommand(myOleDbCommand, "Products", "[{0}]", "?")
		Return provider
	End Function

    <STAThread>
    Public Shared Sub Main()
        SetProcessDPIAware()
        Application.EnableVisualStyles()
        Application.Run(New Form1())
    End Sub
    <System.Runtime.InteropServices.DllImport("user32.dll")>
    Private Shared Function SetProcessDPIAware() As Boolean
    End Function

    Private Sub MenuItem2_Click(sender As Object, e As System.EventArgs)
        Close()
    End Sub

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles button1.Click
        'now bind to the DataProvider
        LL.DataSource = CreateDbCommandSetDataProvider()

        Try
            LL.AutoProjectFile = "simple_label.lbl"
            LL.AutoProjectType = LlProject.Label
            LL.AutoShowSelectFile = False
            LL.Design()
        Catch LlException As ListLabelException
            ' Catch Exceptions
            MessageBox.Show("Information: " & LlException.Message & vbLf & vbLf & "This information was generated by a List & Label custom exception.", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information)
        End Try

    End Sub

    Private Sub Button2_Click(sender As Object, e As EventArgs) Handles button2.Click
        'now bind to the DataProvider
        LL.DataSource = CreateDbCommandSetDataProvider()

        Try
            LL.AutoProjectFile = "simple_label.lbl"
            LL.AutoProjectType = LlProject.Label
            LL.AutoShowSelectFile = False
            LL.Print()
        Catch LlException As ListLabelException
            ' Catch Exceptions
            MessageBox.Show("Information: " & LlException.Message & vbLf & vbLf & "This information was generated by a List & Label custom exception.", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information)
        End Try
    End Sub
End Class
