#if !defined(AFX_LLVIEWCTRL_H__3F72C38C_5D6A_4AD5_B6F7_C7618D9F1B9A__INCLUDED_)
#define AFX_LLVIEWCTRL_H__3F72C38C_5D6A_4AD5_B6F7_C7618D9F1B9A__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLlViewCtrl wrapper class

class CLlViewCtrl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CLlViewCtrl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x28ebe213, 0xe7c7, 0x11d0, { 0xb1, 0x83, 0x00, 0x40, 0xe9, 0x94, 0xb5, 0x8F } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	BOOL GetToolbarEnabled();
	void SetToolbarEnabled(BOOL bNewValue);
	CString GetSaveAsFilePath();
	void SetSaveAsFilePath(LPCTSTR lpszNewValue);
	CString GetFileURL();
	void SetFileURL(LPCTSTR lpszNewValue);
	unsigned long GetBackColor();
	void SetBackColor(unsigned long newValue);
	void ZoomTimes2();
	void ZoomRevert();
	void ZoomReset();
	void GotoFirst();
	void GotoLast();
	void GotoPrev();
	void GotoNext();
	void SetZoom(long nPercentage);
	void RefreshToolbar();
	void SetOptionString(LPCTSTR sOption, LPCTSTR sValue);
	void PrintCurrentPage(long _hDC);
	void PrintAllPages(BOOL bShowPrintOptions);
	CString GetOptionString(LPCTSTR sOption);
	LPDISPATCH GetToolbarButtons();
	BOOL GetCanClose();
	long GetPages();
	void SaveAs();
	long GetVersion();
	BOOL GetEnabled();
	void SetEnabled(BOOL bNewValue);
	void SendTo();
	BOOL GetAsyncDownload();
	void SetAsyncDownload(BOOL bNewValue);
	void PrintPage(long nPage, long _hDC);
	long GetCurrentPage();
	void SetCurrentPage(long nNewValue);
	BOOL GetShowExitButton();
	void SetShowExitButton(BOOL bNewValue);
	BOOL GetShowThumbnails();
	void SetShowThumbnails(BOOL bNewValue);
	long GetLanguage();
	void SetLanguage(long nNewValue);
	long GetHWnd();
	BOOL GetSlideshowMode();
	void SetSlideshowMode(BOOL bNewValue);
	BOOL GetShowUnprintableArea();
	void SetShowUnprintableArea(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LLVIEWCTRL_H__3F72C38C_5D6A_4AD5_B6F7_C7618D9F1B9A__INCLUDED_)
