<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>false</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="combit.ListLabel31">
      <HintPath>..\..\Assemblies\combit.ListLabel31.dll</HintPath>
    </Reference>
    <Reference Include="combit.ListLabel31.ReportServerIntegration">
      <HintPath>..\..\Assemblies\combit.ListLabel31.ReportServerIntegration.dll</HintPath>
    </Reference>
    <Reference Include="combit.ReportServer31.ClientApi">
      <HintPath>..\..\Assemblies\combit.ReportServer31.ClientApi.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
