using combit.Reporting;
using combit.Reporting.Dom;

using Microsoft.VisualBasic.FileIO;

using System.Data;
using System.Data.OleDb;
using System.Runtime.InteropServices.JavaScript;

namespace Unicode
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            // Change Directory - needed while running within the IDE
            if (!File.Exists("Address.mdb"))
            {
                Directory.SetCurrentDirectory(@"..\..\..\..\..\..\Report Files");
            }

            // Do not modify variables
            //LL.Core.LlSetOption(LlOption.XlatVarnames, 0);

        }

        // create Dataset from address.mdb
        private static DataSet CreateDataSet()
        {
            DataSet ds = new();
            string connectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + Path.GetDirectoryName(Application.ExecutablePath) + @"..\..\..\..\..\..\..\Report Files\Address.mdb";
            OleDbConnection myOledbConnection = new(connectionString);
            myOledbConnection.Open();

            OleDbDataAdapter dataAdapter;
            dataAdapter = new OleDbDataAdapter(new OleDbCommand("SELECT * FROM Persons", myOledbConnection));
            dataAdapter.FillSchema(ds, SchemaType.Source, "Persons");
            dataAdapter.Fill(ds, "Persons");

            return ds;
        }

        private void Button1_Click(object sender, EventArgs e)
        {
            string projectPath = Path.GetDirectoryName(Application.ExecutablePath) + @"..\..\..\..\..\..\..\Report Files\Cross Platform\";

            // Following best practices, we are using a new instance for every job
            using ListLabel LL = new();
            // Now bind to the DataSet
            LL.SetDataBinding(CreateDataSet(), string.Empty);

            try
            {
                if (rbLabel.Checked)
                {
                    LL.AutoProjectFile = Path.Combine(projectPath, "simple_label_unicode.json");
                }
                else if (rbList.Checked)
                {
                    LL.AutoProjectFile = Path.Combine(projectPath, "simple_list_unicode.json");
                }

                // Create export configuration
                ExportConfiguration exportConfiguration = new(LlExportTarget.Pdf, Path.Combine(projectPath, "export.pdf"), LL.AutoProjectFile)
                {
                    ShowResult = true
                };

                // Start export
                LL.Export(exportConfiguration);

                LL.Dispose();
            }
            catch (ListLabelException LlException)
            {
                // Catch Exceptions
                MessageBox.Show("Information: " + LlException.Message + "\n\nThis information was generated by a List & Label custom exception.", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }
    }
}
