'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace WebReporting
    
    Partial Public Class HTML5Viewer
        
        '''<summary>
        '''LTViewerTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LTViewerTitle As Global.System.Web.UI.WebControls.Literal
        
        '''<summary>
        '''Html5ViewerControl1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Html5ViewerControl1 As Global.combit.ListLabel25.Web.Html5ViewerControl
        
        '''<summary>
        '''LabelError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LabelError As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
