<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWpf>true</UseWpf>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<Deterministic>false</Deterministic>
  </PropertyGroup>

 <ItemGroup>
   <Reference Include="combit.ListLabel31">
     <HintPath>..\..\Assemblies\combit.ListLabel31.dll</HintPath>
   </Reference>
   <Reference Include="combit.ListLabel31.Wpf">
     <HintPath>..\..\Assemblies\combit.ListLabel31.Wpf.dll</HintPath>
   </Reference>
 </ItemGroup>
</Project>
