'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:2.0.50727.3615
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MapsObject.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die City ähnelt.
        '''</summary>
        Friend ReadOnly Property City() As String
            Get
                Return ResourceManager.GetString("City", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Name of the City ähnelt.
        '''</summary>
        Friend ReadOnly Property CityDescr() As String
            Get
                Return ResourceManager.GetString("CityDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Coordinate Evaluation Type ähnelt.
        '''</summary>
        Friend ReadOnly Property CoordinateEvaluationType() As String
            Get
                Return ResourceManager.GetString("CoordinateEvaluationType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Used Type of Coordinate Evaluation (Geocoding or Coordinates) ähnelt.
        '''</summary>
        Friend ReadOnly Property CoordinateEvaluationTypeDescr() As String
            Get
                Return ResourceManager.GetString("CoordinateEvaluationTypeDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Latitude ähnelt.
        '''</summary>
        Friend ReadOnly Property Latitude() As String
            Get
                Return ResourceManager.GetString("Latitude", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Latitude for dislaying ähnelt.
        '''</summary>
        Friend ReadOnly Property LatitudeDescr() As String
            Get
                Return ResourceManager.GetString("LatitudeDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Longitude ähnelt.
        '''</summary>
        Friend ReadOnly Property Longitude() As String
            Get
                Return ResourceManager.GetString("Longitude", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Longitude for displaying ähnelt.
        '''</summary>
        Friend ReadOnly Property LongitudeDescr() As String
            Get
                Return ResourceManager.GetString("LongitudeDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Map Type ähnelt.
        '''</summary>
        Friend ReadOnly Property MapType() As String
            Get
                Return ResourceManager.GetString("MapType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Used Map Type ähnelt.
        '''</summary>
        Friend ReadOnly Property MapTypeDescr() As String
            Get
                Return ResourceManager.GetString("MapTypeDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Resolution ähnelt.
        '''</summary>
        Friend ReadOnly Property Resolution() As String
            Get
                Return ResourceManager.GetString("Resolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Resolution for displaying ähnelt.
        '''</summary>
        Friend ReadOnly Property ResolutionDescr() As String
            Get
                Return ResourceManager.GetString("ResolutionDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show Tooltip ähnelt.
        '''</summary>
        Friend ReadOnly Property ShowToolTip() As String
            Get
                Return ResourceManager.GetString("ShowToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Defines whether the Tooltip is displayed ähnelt.
        '''</summary>
        Friend ReadOnly Property ShowToolTipDescr() As String
            Get
                Return ResourceManager.GetString("ShowToolTipDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tooltip Background ähnelt.
        '''</summary>
        Friend ReadOnly Property ToolTipBg() As String
            Get
                Return ResourceManager.GetString("ToolTipBg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Color for Tooltip Background ähnelt.
        '''</summary>
        Friend ReadOnly Property ToolTipBgDescr() As String
            Get
                Return ResourceManager.GetString("ToolTipBgDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tooltip font ähnelt.
        '''</summary>
        Friend ReadOnly Property ToolTipFont() As String
            Get
                Return ResourceManager.GetString("ToolTipFont", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Used Font for Tooltip ähnelt.
        '''</summary>
        Friend ReadOnly Property ToolTipFontDescr() As String
            Get
                Return ResourceManager.GetString("ToolTipFontDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Tooltip Text ähnelt.
        '''</summary>
        Friend ReadOnly Property ToolTipText() As String
            Get
                Return ResourceManager.GetString("ToolTipText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Text displayed in Tooltip ähnelt.
        '''</summary>
        Friend ReadOnly Property ToolTipTextDescr() As String
            Get
                Return ResourceManager.GetString("ToolTipTextDescr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zoom Level ähnelt.
        '''</summary>
        Friend ReadOnly Property Zoom() As String
            Get
                Return ResourceManager.GetString("Zoom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Zoom Level for displaying ähnelt.
        '''</summary>
        Friend ReadOnly Property ZoomDescr() As String
            Get
                Return ResourceManager.GetString("ZoomDescr", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
